const fs = require("fs");
const axios = require("axios");
const cheerio = require("cheerio");

// 🔥 diccionarios
const typeMap = {
  Grass: "Planta",
  Poison: "Veneno",
  Fire: "Fuego",
  Water: "Agua",
  Electric: "Eléctrico",
  Ice: "Hielo",
  Fighting: "Pelea",
  Ground: "Tierra",
  Flying: "Volador",
  Psychic: "Psíquico",
  Bug: "Insecto",
  Rock: "Roca",
  Ghost: "Fantasma",
  Dragon: "Dragón",
  Dark: "Siniestro",
  Steel: "Acero",
  Fairy: "Hada",
  Normal: "Normal"
};

const moveMap = {
"Acid":"Ácido", 
"Acid Spray":"Bomba Ácida", 
"Acrobatics":"Acrobacia", 
"Aerial Ace":"As Aéreo", 
"Aeroblast":"Aerochorro", 
"Air Cutter":"Aire Cortante", 
"Air Slash":"Corte Aéreo", 
"Ancient Power":"Poder Antiguo", 
"Aqua Jet":"Acuajet", 
"Aqua Step":"Danza Acuática", 
"Aqua Tail":"Cola de Agua", 
"Astonish":"Impresionar", 
"Aura Sphere":"Aura Esfera", 
"Aura Wheel":"Rueda Aural", 
"Aura Wheel":"Rueda Aural", 
"Aurora Beam":"Rayo Aurora", 
"Avalanche":"Alud", 
"Beak Blast":"Pico Cañón", 
"Behemoth Bash":"Golpe Supremo", 
"Behemoth Blade":"Corte Supermo", 
"Bite":"Mordida", 
"Blast Burn":"Anillo de Fuego", 
"Blaze Kick":"Patada Ígnea", 
"Bleakwind Storm":"Vendaval Gélido", 
"Blizzard":"Ventisca", 
"Body Slam":"Golpe de Cuerpo", 
"Bone Club":"Maza de Hueso", 
"Boomburst":"Estruendo", 
"Brave Bird":"Ave Brava", 
"Breaking Swipe":"Vasto Impacto", 
"Brick Break":"Karatazo", 
"Brine":"Agua Salada", 
"Brutal Swing":"Giro Vil", 
"Bubble":"Burbuja", 
"Bubble Beam":"Rayo Burbuja", 
"Bug Bite":"Picadura", 
"Bug Buzz":"Zumbido", 
"Bulldoze":"Terratemblor", 
"Bullet Punch":"Puño Bala", 
"Bullet Seed":"Bala Semilla", 
"Charge Beam":"Rayo Carga", 
"Charm":"Encanto", 
"Chilling Water":"Agua Fría", 
"Clanging Scales":"Fragor Escamas", 
"Close Combat":"Cuerpo a Cuerpo", 
"Confusion":"Confusión", 
"Counter":"Contraataque", 
"Crabhammer":"Martillazo", 
"Cross Chop":"Golpe Cruzado", 
"Cross Poison":"Veneno X", 
"Crunch":"Triturar", 
"Crush Grip":"Garra Aplastante", 
"Cut":"Corte", 
"Darkest Lariat":"Lariat Oscuro", 
"Dark Pulse":"Pulso Oscuro", 
"Dazzling Gleam":"Brillo Mágico", 
"Dig":"Excavar", 
"Disarming Voice":"Voz Encantadora", 
"Discharge":"Chispazo", 
"Doom Desire":"Deseo Final", 
"Double Iron Bash":"Ferropuño Doble", 
"Double Kick":"Doble Patada", 
"Draco Meteor":"Meteoro Dragón", 
"Dragon Ascent":"Ascenso Dracónico", 
"Dragon Breath":"Aliento de Dragón", 
"Dragon Claw":"Garra Dragón", 
"Dragon Energy":"Dracoenergía", 
"Dragon Pulse":"Pulso Dragón", 
"Dragon Tail":"Cola de Dragón", 
"Draining Kiss":"Beso Drenaje", 
"Drain Punch":"Puño Drenaje", 
"Drill Peck":"Pico Taladro", 
"Drill Run":"Taladradora", 
"Drum Beating":"Batería Asalto", 
"Dynamax Cannon":"Cañon Dinamax", 
"Dynamic Punch":"Puño Dinámico", 
"Earthquake":"Terremoto", 
"Earth Power":"Poder Terrestre", 
"Ember":"Brasas", 
"Energy Ball":"Bola de Energía", 
"Extrasensory":"Extrasensorial", 
"Fairy Wind":"Viento Feérico", 
"Feather Dance":"Danza de Plumas", 
"Feint Attack":"Ataque Finta", 
"Fell Stinger":"Aguijón Letal", 
"Fire Blast":"Llamarada", 
"Fire Fang":"Colmillo de Fuego", 
"Fire Punch":"Puño Fuego", 
"Fire Spin":"Giro Fuego", 
"Flamethrower":"Lanzallamas", 
"Flame Burst":"Golpe de Fuego", 
"Flame Charge":"Carga de Fuego", 
"Flame Wheel":"Rueda de Fuego", 
"Flash Cannon":"Cañón Destello", 
"Flower Trick":"Truco Floral", 
"Fly":"Vuelo", 
"Flying Press":"Plancha Voladora", 
"Focus Blast":"Ataque Centrado", 
"Force Palm":"Fuerza de Palma", 
"Foul Play":"Juego Sucio", 
"Freeze Shock":"Rayo Gélido", 
"Frenzy Plant":"Planta Feroz", 
  "Frost Breath": "Vaho Helado",
  "Frustration": "Frustración",
  "Fury Cutter": "Corte Furia",
  "Fusion Bolt": "Rayo Fusión",
  "Fusion Flare": "Llama Fusión",
  "Future Sight": "Premonición",
  "Geomancy": "Geocontrol",
  "Giga Drain": "Gigadrenado",
  "Giga Impact": "Gigaimpacto",
  "Glaciate": "Mundo Gélido",
  "Grass Knot": "Hierba Lazo",
  "Gunk Shot": "Lanzamugre",
  "Gust": "Ráfaga",
  "Gyro Ball": "Giro Bola",
  "Heart Stamp": "Arrumaco",
  "Heat Wave": "Onda Ígnea",
  "Heavy Slam": "Cuerpo Pesado",
  "Hex": "Infortunio",
  "Hidden Power": "Poder Oculto",
  "High Horsepower": "Fuerza Equina",
  "High Jump Kick": "Patada Salto Alta",
  "Horn Attack": "Cornada",
  "Hurricane": "Huracán",
  "Hydro Cannon": "Hidrocañón",
  "Hydro Pump": "Hidrobomba",
  "Hydro Pump Blastoise": "Hidrobomba",
  "Hyper Beam": "Hiperrayo",
  "Hyper Fang": "Hipercolmillo",
  "Ice Beam": "Rayo Hielo",
  "Ice Burn": "Llama Gélida",
  "Ice Fang": "Colmillo Hielo",
  "Ice Punch": "Puño Hielo",
  "Ice Shard": "Canto Helado",
  "Icicle Spear": "Carámbano",
  "Icy Wind": "Viento Hielo",
  "Incinerate": "Calcinación",
  "Infestation": "Infestación",
  "Iron Head": "Cabeza de Hierro",
  "Iron Tail": "Cola Férrea",
  "Karate Chop": "Golpe Karate",
  "Last Resort": "Última Baza",
  "Leafage": "Follaje",
  "Leaf Blade": "Hoja Aguda",
  "Leaf Storm": "Lluevehojas",
  "Leaf Tornado": "Ciclón de Hojas",
  "Lick": "Lengüetazo",
  "Liquidation": "Hidroariete",
  "Lock On": "Fijar Blanco",
  "Low Kick": "Patada Baja",
  "Low Sweep": "Puntapié",
  "Lunge": "Plancha",
  "Luster Purge": "Brillo Mágico",
  "Magical Leaf": "Hoja Mágica",
  "Magma Storm": "Tormenta Magma",
  "Magnet Bomb": "Bomba Imán",
  "Megahorn": "Megacuerno",
  "Mega Drain": "Megadrenado",
  "Metal Claw": "Garra Metal",
  "Metal Sound": "Eco Metálico",
  "Meteor Beam": "Rayo Meteórico",
  "Meteor Mash": "Puño Meteoro",
  "Mind Blown": "Cabeza Sorpresa",
  "Mirror Coat": "Manto Espejo",
  "Mirror Shot": "Disparo Espejo",
  "Mist Ball": "Bola Neblina",
  "Moonblast": "Fuerza Lunar",
  "Moongeist Beam": "Rayo Umbrío",
  "Muddy Water": "Agua Lodosa",
  "Mud Bomb": "Bomba Fango",
  "Mud Shot": "Disparo Lodo",
  "Mud Slap": "Bofetón Lodo",
  "Mystical Fire": "Llama Embrujada",
  "Nature's Madness": "Furia Natural",
  "Night Shade": "Tinieblas",
  "Night Slash": "Tajo Umbrío",
  "Oblivion Wing": "Ala Mortífera",
  "Obstruct": "Obstrucción",
  "Octazooka": "Pulpocañón",
  "Ominous Wind": "Viento Aciago",
  "Origin Pulse": "Pulso Primigenio",
  "Outrage": "Enfado",
  "Overheat": "Supercalor",
  "Parabolic Charge": "Carga Parábola",
  "Payback": "Revancha",
  "Peck": "Picotazo",
  "Petal Blizzard": "Tormenta Floral",
  "Play Rough": "Juego Rudo",
  "Poison Fang": "Colmillo Veneno",
  "Poison Jab": "Puya Nociva",
  "Poison Sting": "Picotazo Veneno",
  "Poltergeist": "Poltergeist",
  "Pound": "Destructor",
  "Powder Snow": "Polvo de Nieve",
  "Power Gem": "Joya de Luz",
  "Power-Up Punch": "Puño Incremento",
  "Power Whip": "Latigazo",
  "Precipice Blades": "Filo del Abismo",
  "Present": "Presente",
  "Psybeam": "Psicorrayo",
  "Psychic": "Fuerza Psíquica",
  "Psychic Fangs": "Colmillo Psíquico",
  "Psycho Boost": "Psicoataque",
  "Psycho Cut": "Psicocorte",
  "Psyshock": "Psicocarga",
  "Psystrike": "Onda Mental",
  "Psywave": "Psicoonda",
  "Pyro Ball": "Balón Ígneo",
  "Quick Attack": "Ataque Rápido",
  "Rage Fist": "Puño Furia",
  "Razor Leaf": "Hoja Afilada",
  "Razor Shell": "Coraza Afilada",
  "Rest": "Descanso",
  "Return": "Retribución",
  "Roar of Time": "Distorsión Temporal",
  "Rock Blast": "Pedrada",
  "Rock Slide": "Avalancha",
  "Rock Smash": "Golpe Roca",
  "Rock Throw": "Lanzarrocas",
  "Rock Tomb": "Tumba Rocas",
  "Rock Wrecker": "Romperrocas",
  "Rollout": "Rodada",
  "Sacred Fire": "Fuego Sagrado",
  "Sacred Sword": "Espada Santa",
  "Sandsear Storm": "Tifón de Arena",
  "Sand Attack": "Ataque Arena",
  "Sand Tomb": "Tumba de Arena",
  "Scald": "Escaldar",
  "Scorching Sands": "Arenas Ardientes",
  "Scratch": "Arañazo",
  "Secret Sword": "Espada Secreta",
  "Seed Bomb": "Bomba Germen",
  "Seed Flare": "Fogonazo Floral",
  "Shadow Ball": "Bola Sombra",
  "Shadow Bone": "Hueso Sombrío",
  "Shadow Claw": "Garra de Sombra",
  "Shadow Force": "Golpe Umbrío",
  "Shadow Punch": "Puño Sombra",
  "Shadow Sneak": "Sombra Vil",
  "Signal Beam": "Doble Rayo",
  "Silver Wind": "Viento Plata",
  "Skull Bash": "Cabezazo",
  "Sky Attack": "Ataque Aéreo",
  "Sludge": "Residuos",
  "Sludge Bomb": "Bomba Lodo",
  "Sludge Wave": "Onda Tóxica",
  "Smack Down": "Antiaéreo",
  "Snarl": "Alarido",
  "Solar Beam": "Rayo Solar",
  "Spacial Rend": "Corte Vacío",
  "Spark": "Chispa",
  "Sparkling Aria": "Aria Burbuja",
  "Spirit Shackle": "Puntada Sombría",
  "Splash": "Salpicadura",
  "Springtide Storm (Speculative)": "Tormenta Primaveral",
  "Steel Wing": "Ala de Acero",
  "Stomp": "Pisotón",
  "Stone Edge": "Roca Afilada",
  "Struggle": "Forcejeo",
  "Struggle Bug": "Estoicismo",
  "Submission": "Sumisión",
  "Sucker Punch": "Golpe Bajo",
  "Sunsteel Strike": "Meteoimpacto",
  "Superpower": "Fuerza Bruta",
  "Surf": "Surf",
  "Swift": "Rapidez",
  "Synchronoise": "Sincrorruido",
  "Tackle": "Placaje",
  "Take Down": "Derribo",
  "Techno Blast (Burn)": "Tecno Shock (Fuego)",
  "Techno Blast (Chill)": "Tecno Shock (Hielo)",
  "Techno Blast (Douse)": "Tecno Shock (Agua)",
  "Techno Blast (Normal)": "Tecno Shock (Normal)",
  "Techno Blast (Shock)": "Tecno Shock (Eléctrico)",
  "Thunder": "Trueno",
  "Thunderbolt": "Rayo",
  "Thunder Cage": "Electrojaula",
  "Thunder Fang": "Colmillo Trueno",
  "Thunder Punch": "Puño Trueno",
  "Thunder Shock": "Impactrueno",
  "Torch Song": "Canto Ardiente",
  "Trailblaze": "Abrecaminos",
  "Triple Axel": "Triple Axel",
  "Tri Attack": "Triataque",
  "Twister": "Tornado",
  "Upper Hand": "Palma Rauda",
  "Vise Grip": "Agarre",
  "Vine Whip": "Látigo Cepa",
  "Volt Switch": "Voltiocambio",
  "Volt Tackle": "Placaje Eléctrico",
  "V-Create": "V de Fuego",
  "Waterfall": "Cascada",
  "Water Gun": "Pistola de Agua",
  "Water Pulse": "Hidropulso",
  "Water Shuriken": "Shuriken de Agua",
  "Weather Ball - (Fire)": "Meteorobola (Fuego)",
  "Weather Ball - (Ice)": "Meteorobola (Hielo)",
  "Weather Ball - (Normal)": "Meteorobola (Normal)",
  "Weather Ball - (Rock)": "Meteorobola (Roca)",
  "Weather Ball - (Water)": "Meteorobola (Agua)",
  "Wildbolt Storm": "Electormenta",
  "Wild Charge": "Carga Salvaje",
  "Wing Attack": "Ataque Ala",
  "Wrap": "Constricción",
  "X-Scissor": "Tijera X",
  "Yawn": "Bostezo",
  "Zap Cannon": "Electrocañón",
  "Zen Headbutt": "Cabezazo Zen"
};

// 🔥 función translate
const translate = (pokemonList) => {
  return pokemonList.map(p => ({
    name: p.name,
    baseName: p.baseName, 
    types: p.types.map(t => typeMap[t] || t),
    fastMoves: p.fastMoves.map(m => moveMap[m] || m),
    chargedMoves: p.chargedMoves.map(m => moveMap[m] || m),
    sprite: p.sprite 
  }));
};



async function scrapePokemon() {
  const url = "https://pokemondb.net/go/pokedex";
  const { data } = await axios.get(url);

  const $ = cheerio.load(data);

  const pokemon = [];

  $("table tbody tr").each((i, el) => {
    const name = $(el).find("a.ent-name").text();
const form = $(el).find("small").text();

// 🔥 limpiar nombre de forma
const cleanForm = form
  .replace("Form", "")
  .replace("Alolan", "Alola")
  .replace("Galarian", "Galar")
  .replace("Hisuian", "Hisui")
  .replace("Paldean", "Paldea")
  .trim();


const fullName = cleanForm ? `${name} (${cleanForm})` : name;



const baseName = name;
    if (!name) return;
    if (form.toLowerCase().includes("mega")) return;

    const types = [];
    $(el).find(".type-icon").each((i, t) => {
      types.push($(t).text());
    });

    const getMoves = (td) =>
      $(td)
        .contents()
        .map((i, el) => $(el).text().trim())
        .get()
        .filter(m => m && !m.includes("%"))
        .map(m => m.replace(/\(.*?\)/g, "").trim());

    const fastMoves = getMoves($(el).find("td").eq(8));
    const chargedMoves = getMoves($(el).find("td").eq(9));
    const sprite = $(el).find("img").attr("src");
    pokemon.push({
  name: fullName,
  baseName,
  types,
  fastMoves,
  chargedMoves,
  sprite
});
  });

  //  TRADUCCIÓN
  const translated = translate(pokemon);

  // VA TODO A LA CARPETA PRINCIPAL al json ese
  fs.writeFileSync("pokemon-es.json", JSON.stringify(translated, null, 2));
}

scrapePokemon();